-- Open TextEdit with clipboard contents
-- App: Textedit
-- Usage: osascript scripts/workflows/textedit/textedit-new-from-clipboard.applescript
-- Generated by workflow-gen.py

set clipContent to the clipboard as text
tell application "TextEdit"
    activate
    make new document with properties {text:clipContent}
end tell
