-- Count words in frontmost TextEdit document
-- App: Textedit
-- Usage: osascript scripts/workflows/textedit/textedit-word-count.applescript
-- Generated by workflow-gen.py

tell application "TextEdit"
    set t to text of front document
    set wc to count of words of t
    display notification (wc as text) & " words" with title "TextEdit"
end tell
