-- Open TextEdit with clipboard contents
-- App: Textedit
-- Usage: osascript scripts/workflows/textedit/textedit-new-from-clipboard.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

set clipContent to the clipboard as text
tell application "TextEdit"
    activate
    make new document with properties {text:clipContent}
end tell
