-- Create a new blank TextEdit document
-- App: Textedit
-- Usage: osascript scripts/workflows/textedit/textedit-new-document.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "TextEdit"
    activate
    make new document
end tell
