-- Run a command in a new Terminal tab
-- App: Terminal
-- Usage: osascript scripts/workflows/terminal/terminal-run-command.applescript
-- Generated by workflow-gen.py

tell application "Terminal"
    activate
    set cmd to text returned of (display dialog "Command:" default answer "")
    do script cmd
end tell
