-- Open a new Terminal tab
-- App: Terminal
-- Usage: osascript scripts/workflows/terminal/terminal-new-tab.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Terminal"
    activate
    do script ""
end tell
