-- Open Terminal tab at a specific directory
-- App: Terminal
-- Usage: osascript scripts/workflows/terminal/terminal-new-tab-at-path.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    if (count of Finder windows) > 0 then
        set p to POSIX path of (target of front Finder window as alias)
    else
        set p to POSIX path of (path to home folder)
    end if
end tell
tell application "Terminal"
    activate
    do script "cd " & quoted form of p
end tell
