-- Open a new Terminal tab
-- App: Terminal
-- Usage: osascript scripts/workflows/terminal/terminal-new-tab.applescript
-- Generated by workflow-gen.py

tell application "Terminal"
    activate
    do script ""
end tell
