-- Open Sound settings pane
-- App: System Settings
-- Triggers: sound, open, settings, pane
-- Category: System Settings
-- Usage: osascript scripts/workflows/system-settings/system-settings-sound.applescript
-- Generated by workflow-gen.py

-- Concept: do shell script "command"
--   Runs a shell command from AppleScript and returns stdout as text.

do shell script "open 'x-apple.systempreferences:com.apple.Sound-Settings.extension'"
