-- Open General settings pane
-- App: System Settings
-- Usage: osascript scripts/workflows/system-settings/system-settings-general.applescript
-- Generated by workflow-gen.py

-- Concept: do shell script "command"
--   Runs a shell command from AppleScript and returns stdout as text.

do shell script "open 'x-apple.systempreferences:com.apple.systempreferences.GeneralSettings'"
