-- Flag the selected message
-- App: Mail
-- Usage: osascript scripts/workflows/mail/mail-flag-selected.applescript
-- Generated by workflow-gen.py

tell application "Mail"
    set sel to selection
    repeat with m in sel
        set flagged status of m to true
    end repeat
    display notification "Flagged " & (count of sel) & " message(s)" with title "Mail"
end tell
