-- Compose a new message to a specific address
-- App: Mail
-- Usage: osascript scripts/workflows/mail/mail-compose-to.applescript
-- Generated by workflow-gen.py

tell application "Mail"
    activate
    set addr to text returned of (display dialog "Send to:" default answer "")
    set newMsg to make new outgoing message with properties {visible:true, subject:""}
    tell newMsg
        make new to recipient at end of to recipients with properties {address:addr}
    end tell
end tell
