-- Open a new blank compose window
-- App: Mail
-- Usage: osascript scripts/workflows/mail/mail-compose.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Mail"
    activate
    set newMsg to make new outgoing message with properties {visible:true}
end tell
