-- Forward the selected message
-- App: Mail
-- Usage: osascript scripts/workflows/mail/mail-forward-selected.applescript
-- Generated by workflow-gen.py

tell application "Mail"
    activate
    set sel to selection
    if (count of sel) > 0 then
        set m to item 1 of sel
        forward m opening window yes
    end if
end tell
