-- Get the subject of the latest message in inbox
-- App: Mail
-- Usage: osascript scripts/workflows/mail/mail-read-latest-subject.applescript
-- Generated by workflow-gen.py

tell application "Mail"
    set msgs to messages of inbox
    if (count of msgs) > 0 then
        set m to item 1 of msgs
        set s to subject of m
        set f to sender of m
        display notification f with title s
    else
        display notification "Inbox is empty" with title "Mail"
    end if
end tell
