-- Check for new mail
-- App: Mail
-- Usage: osascript scripts/workflows/mail/mail-check-mail.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Mail" to check for new mail
