-- Show unread mail count as notification
-- App: Mail
-- Usage: osascript scripts/workflows/mail/mail-unread-count.applescript
-- Generated by workflow-gen.py

tell application "Mail"
    set total to 0
    repeat with a in every account
        repeat with m in every mailbox of a
            set total to total + unread count of m
        end repeat
    end repeat
    display notification (total as text) & " unread messages" with title "Mail"
end tell
