-- Mark all inbox messages as read
-- App: Mail
-- Usage: osascript scripts/workflows/mail/mail-mark-all-read.applescript
-- Generated by workflow-gen.py

tell application "Mail"
    set msgs to messages of inbox whose read status is false
    repeat with m in msgs
        set read status of m to true
    end repeat
    display notification "Marked " & (count of msgs) & " messages read" with title "Mail"
end tell
