-- Show Safari bookmarks
-- App: Safari
-- Usage: osascript scripts/workflows/safari/safari-show-bookmarks.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Safari"
    activate
    show bookmarks
end tell
