-- Search the web using Safari
-- App: Safari
-- Usage: osascript scripts/workflows/safari/safari-search-web.applescript
-- Generated by workflow-gen.py

tell application "Safari"
    activate
    set q to text returned of (display dialog "Search:" default answer "")
    search the web for q
end tell
