-- Open a URL in a new Safari tab
-- App: Safari
-- Usage: osascript scripts/workflows/safari/safari-open-url.applescript
-- Generated by workflow-gen.py

tell application "Safari"
    activate
    set u to text returned of (display dialog "URL:" default answer "https://")
    tell front window
        set newTab to make new tab with properties {URL:u}
    end tell
end tell
