-- Copy the URL of the current Safari tab to clipboard
-- App: Safari
-- Usage: osascript scripts/workflows/safari/safari-current-url.applescript
-- Generated by workflow-gen.py

tell application "Safari"
    set u to URL of current tab of front window
    set the clipboard to u
    display notification u with title "URL Copied"
end tell
