-- Copy page source of current tab to clipboard
-- App: Safari
-- Usage: osascript scripts/workflows/safari/safari-page-source.applescript
-- Generated by workflow-gen.py

tell application "Safari"
    set src to source of current tab of front window
    set the clipboard to src
    display notification "Source copied (" & (length of src) & " chars)" with title "Safari"
end tell
