-- Copy the title of the current Safari tab to clipboard
-- App: Safari
-- Usage: osascript scripts/workflows/safari/safari-current-title.applescript
-- Generated by workflow-gen.py

tell application "Safari"
    set t to name of current tab of front window
    set the clipboard to t
    display notification t with title "Title Copied"
end tell
