-- Copy URL and title as markdown link
-- App: Safari
-- Usage: osascript scripts/workflows/safari/safari-current-url-and-title.applescript
-- Generated by workflow-gen.py

tell application "Safari"
    set u to URL of current tab of front window
    set t to name of current tab of front window
    set mdLink to "[" & t & "](" & u & ")"
    set the clipboard to mdLink
    display notification mdLink with title "Markdown Link Copied"
end tell
