-- Close all tabs in the front Safari window
-- App: Safari
-- Usage: osascript scripts/workflows/safari/safari-close-all-tabs.applescript
-- Generated by workflow-gen.py

tell application "Safari"
    tell front window
        set currentTab to current tab
        repeat with t in (every tab whose index is not index of currentTab)
            close t
        end repeat
    end tell
end tell
