-- Add the current page to Reading List
-- App: Safari
-- Usage: osascript scripts/workflows/safari/safari-add-reading-list.applescript
-- Generated by workflow-gen.py

tell application "Safari"
    set u to URL of current tab of front window
    set t to name of current tab of front window
    add reading list item u with title t
    display notification t with title "Added to Reading List"
end tell
