-- Open a file in Preview via choose dialog
-- App: Preview
-- Usage: osascript scripts/workflows/preview/preview-open-file.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

set f to choose file with prompt "Choose a file to open in Preview:" of type {"public.image", "com.adobe.pdf"}
tell application "Preview"
    activate
    open f
end tell
