-- Create a reminder from clipboard text
-- App: Reminders
-- Usage: osascript scripts/workflows/reminders/reminders-reminder-from-clipboard.applescript
-- Generated by workflow-gen.py

set clipText to the clipboard as text
tell application "Reminders"
    tell default list
        make new reminder with properties {name:clipText}
    end tell
    display notification "Reminder: " & clipText with title "Reminders"
end tell
