-- Create a reminder due today
-- App: Reminders
-- Usage: osascript scripts/workflows/reminders/reminders-reminder-due-today.applescript
-- Generated by workflow-gen.py

tell application "Reminders"
    set t to text returned of (display dialog "Reminder (due today):" default answer "")
    tell default list
        make new reminder with properties {name:t, due date:current date}
    end tell
    display notification "Due today: " & t with title "Reminders"
end tell
