-- Create a quick reminder
-- App: Reminders
-- Usage: osascript scripts/workflows/reminders/reminders-quick-reminder.applescript
-- Generated by workflow-gen.py

tell application "Reminders"
    set t to text returned of (display dialog "Reminder:" default answer "")
    tell default list
        make new reminder with properties {name:t}
    end tell
    display notification "Created: " & t with title "Reminders"
end tell
