-- Emails the contents of a tab.
-- App: Safari
-- Usage: osascript scripts/auto-workflows/safari/safari-email-contents.applescript
-- Auto-generated by auto-gen.py
-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Safari"
    email contents
end tell
display notification "Done" with title "Safari: email contents"
