-- Open a new Finder window at Downloads
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-new-window-downloads.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    activate
    make new Finder window to folder "Downloads" of home
end tell
