-- Get names of selected Finder items
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-get-selection.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    set sel to selection
    if sel is {} then
        return "No selection"
    end if
    set names to {}
    repeat with f in sel
        set end of names to name of f as text
    end repeat
    return names as text
end tell
