-- Tag selected Finder items red
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-tag-red.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    set sel to selection
    repeat with f in sel
        set label index of f to 2
    end repeat
end tell
