-- Tag selected Finder items orange
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-tag-orange.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    set sel to selection
    repeat with f in sel
        set label index of f to 1
    end repeat
end tell
