-- Open a new Finder window at home folder
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-new-window.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    activate
    make new Finder window to home
end tell
