-- Copy path of selected Finder item to clipboard
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-copy-path.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    set sel to selection
    if sel is {} then
        display notification "No file selected" with title "Finder"
        return
    end if
    set f to item 1 of sel
    set p to POSIX path of (f as alias)
    set the clipboard to p
    display notification p with title "Path Copied"
end tell
