-- Show all desktop icons
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-show-desktop-icons.applescript
-- Generated by workflow-gen.py

do shell script "defaults write com.apple.Finder CreateDesktop true"
do shell script "killall Finder"
