-- Empty the Trash (no confirmation)
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-empty-trash.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Finder"
    empty the trash
end tell
