-- Reveal Downloads folder in Finder
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-reveal-downloads.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    activate
    reveal folder "Downloads" of home
end tell
