-- Close all Finder windows
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-close-all-windows.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    close every window
end tell
