-- Hide all desktop icons
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-hide-desktop-icons.applescript
-- Generated by workflow-gen.py

-- Concept: do shell script "command"
--   Runs a shell command from AppleScript and returns stdout as text.

do shell script "defaults write com.apple.Finder CreateDesktop false"
do shell script "killall Finder"
