-- Get POSIX path of the frontmost Finder window
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-get-window-path.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    if (count of Finder windows) is 0 then
        return POSIX path of (desktop as alias)
    end if
    return POSIX path of (target of front Finder window as alias)
end tell
