-- Sort the frontmost Finder window by name
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-sort-by-name.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    set current view of front Finder window to list view
    set sort column of list view options of front Finder window to column id name column of front Finder window
end tell
