-- Open current working directory in Finder
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-open-current-dir.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    activate
    open (POSIX file (do shell script "pwd") as alias)
end tell
