-- Restart Finder (kf)
-- App: Finder
-- Triggers: restart, finder
-- Category: Finder
-- Usage: osascript scripts/workflows/finder/finder-restart-finder.applescript
-- Generated by workflow-gen.py

-- Concept: do shell script "command"
--   Runs a shell command from AppleScript and returns stdout as text.

do shell script "killall Finder"
