-- Reveal Downloads folder in Finder
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-reveal-downloads.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Finder"
    activate
    reveal folder "Downloads" of home
end tell
