-- Open a new Finder window at Desktop
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-new-window-desktop.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    activate
    make new Finder window to desktop
end tell
