-- Open a new Finder window at home folder
-- App: Finder
-- Triggers: new, window, open, finder, home, folder
-- Category: Finder
-- Usage: osascript scripts/workflows/finder/finder-new-window.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Finder"
    activate
    make new Finder window to home
end tell
