-- Create a new folder in the frontmost Finder window
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-new-folder.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    activate
    set w to target of front Finder window
    set newFolder to make new folder at w
    select newFolder
end tell
