-- Clear tags from selected Finder items
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-tag-clear.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    set sel to selection
    repeat with f in sel
        set label index of f to 0
    end repeat
end tell
