-- Empty the Trash (no confirmation)
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-empty-trash.applescript
-- Generated by workflow-gen.py

tell application "Finder"
    empty the trash
end tell
