-- Close all Finder windows
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-close-all-windows.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Finder"
    close every window
end tell
