-- Clear tags from selected Finder items
-- App: Finder
-- Triggers: tag, clear, tags, selected, finder, items
-- Category: Finder
-- Usage: osascript scripts/workflows/finder/finder-tag-clear.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).
-- Concept: repeat with item in list
--   Loops over each item in a list, like a for-each loop.

tell application "Finder"
    set sel to selection
    repeat with f in sel
        set label index of f to 0
    end repeat
end tell
