-- Reveal a file in Finder for AirDrop sharing
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-airdrop-reveal.applescript
-- Generated by workflow-gen.py

set f to choose file with prompt "Choose file to AirDrop:"
set p to POSIX path of f
do shell script "open -R " & quoted form of p
tell application "Finder" to activate
display notification "Right-click > Share > AirDrop" with title "AirDrop"
