-- Set desktop wallpaper from a file path
-- App: Finder
-- Usage: osascript scripts/workflows/finder/finder-set-wallpaper.applescript
-- Generated by workflow-gen.py

set imgPath to choose file with prompt "Choose wallpaper image:" of type {"public.image"}
tell application "Finder"
    set desktop picture to imgPath
end tell
display notification "Wallpaper changed" with title "Finder"
