-- Open a new Finder window at Downloads
-- App: Finder
-- Triggers: new, window, downloads, open, finder
-- Category: Finder
-- Usage: osascript scripts/workflows/finder/finder-new-window-downloads.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Finder"
    activate
    make new Finder window to folder "Downloads" of home
end tell
