-- Create a new note from clipboard contents
-- App: Notes
-- Usage: osascript scripts/workflows/notes/notes-new-note-from-clipboard.applescript
-- Generated by workflow-gen.py

set clipContent to the clipboard as text
tell application "Notes"
    activate
    tell account "iCloud"
        make new note at folder "Notes" with properties {name:"From Clipboard", body:clipContent}
    end tell
    display notification "Note created from clipboard" with title "Notes"
end tell
