-- Show total note count
-- App: Notes
-- Usage: osascript scripts/workflows/notes/notes-count-notes.applescript
-- Generated by workflow-gen.py

tell application "Notes"
    set c to count of every note
    display notification (c as text) & " notes total" with title "Notes"
end tell
