-- Create a new audio recording document.
-- App: QuickTime Player
-- Usage: osascript scripts/auto-workflows/quicktime-player/quicktime-player-new-audio-recording.applescript
-- Auto-generated by auto-gen.py
-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "QuickTime Player"
    new audio recording
end tell
display notification "Done" with title "QuickTime Player: new audio recording"
