name: "Open Applications Folder"
scope: "com.apple.speech.SystemWideScope"
description: "This command will switch to the Finder and open the Applications folder."
source_library: "Workspace"
source_file: "Finder-Open-ApplicationsFolder.scpt"
siri_phrases:
  - "open [the] applications folder"
applescript: |
  use script "DC-Workspace"
  tell script "DC-Workspace" to getPathForApplicationsDirectory(true)
