-- Clear the clipboard
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-empty-clipboard.applescript
-- Generated by workflow-gen.py

-- Concept: display notification "text" with title "title"
--   Shows a macOS notification banner. Disappears after a few seconds.
-- Concept: set the clipboard to "text"
--   Copies text to the system clipboard, same as Cmd+C.

set the clipboard to ""
display notification "Clipboard cleared" with title "System"
