-- Toggle macOS Dark Mode
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-dark-mode-toggle.applescript
-- Generated by workflow-gen.py

tell application "System Events"
    tell appearance preferences
        set dark mode to not dark mode
    end tell
end tell
