-- Toggle macOS Dark Mode
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-dark-mode-toggle.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "System Events"
    tell appearance preferences
        set dark mode to not dark mode
    end tell
end tell
