-- Take a screenshot of the frontmost window
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-screenshot-window.applescript
-- Generated by workflow-gen.py

-- Concept: do shell script "command"
--   Runs a shell command from AppleScript and returns stdout as text.

do shell script "screencapture -w ~/Desktop/screenshot-" & (do shell script "date +%Y%m%d-%H%M%S") & ".png"
