-- Set system volume to a specific level
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-volume-set.applescript
-- Generated by workflow-gen.py

set v to text returned of (display dialog "Volume (0-100):" default answer "50")
set volume output volume (v as integer)
display notification "Volume: " & v & "%" with title "System"
