-- Lock the screen immediately
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-screen-lock.applescript
-- Generated by workflow-gen.py

-- Concept: do shell script "command"
--   Runs a shell command from AppleScript and returns stdout as text.

do shell script "/System/Library/CoreServices/Menu\\ Extras/User.menu/Contents/Resources/CGSession -suspend"
