-- Show the Dock (autohide off)
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-show-dock.applescript
-- Generated by workflow-gen.py

do shell script "defaults write com.apple.Dock autohide -bool FALSE"
do shell script "killall Dock"
display notification "Dock visible" with title "Dock"
