-- Restart the macOS menu bar (topbar)
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-restart-menu-bar.applescript
-- Generated by workflow-gen.py

do shell script "killall -KILL SystemUIServer"
display notification "Menu bar restarted" with title "System"
