-- Add a spacer tile to the Dock
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-dock-add-spacer.applescript
-- Generated by workflow-gen.py

do shell script "defaults write com.apple.dock persistent-apps -array-add '{"tile-type"="spacer-tile";}'"
do shell script "killall Dock"
display notification "Spacer added" with title "Dock"
