-- Toggle Do Not Disturb (Focus)
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-do-not-disturb.applescript
-- Generated by workflow-gen.py

tell application "System Events"
    tell application process "ControlCenter"
        -- Click the Focus button in Control Center
        click menu bar item "Focus" of menu bar 1
    end tell
end tell
