-- Type text via System Events (paste alternative)
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-type-text.applescript
-- Generated by workflow-gen.py

set t to text returned of (display dialog "Type text:" default answer "")
tell application "System Events"
    keystroke t
end tell
