-- Get the name of the frontmost application
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-get-frontmost-app.applescript
-- Generated by workflow-gen.py

tell application "System Events"
    set frontApp to name of first application process whose frontmost is true
    display notification frontApp with title "Frontmost App"
    set the clipboard to frontApp
end tell
