-- Take a screenshot of a selected area
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-screenshot-area.applescript
-- Generated by workflow-gen.py

do shell script "screencapture -i ~/Desktop/screenshot-" & (do shell script "date +%Y%m%d-%H%M%S") & ".png"
