-- Add Recent Apps stack to the Dock
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-dock-add-recent-apps.applescript
-- Generated by workflow-gen.py

do shell script "defaults write com.apple.dock persistent-others -array-add '{\"tile-data\" = {\"list-type\" = 1;}; \"tile-type\" = \"recents-tile\";}'"
do shell script "killall Dock"
display notification "Recent Apps added to Dock" with title "Dock"
