-- Send a keyboard shortcut to the frontmost app
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-key-shortcut.applescript
-- Generated by workflow-gen.py

-- Example: Cmd+Shift+S (Save As)
tell application "System Events"
    keystroke "s" using {command down, shift down}
end tell
