-- Reset Apple Events daemon (fixes -1712 errors)
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-reset-apple-events.applescript
-- Generated by workflow-gen.py

do shell script "sudo killall -KILL appleeventsd" with administrator privileges
display notification "Apple Events daemon restarted" with title "System"
