-- Hide the Dock (autohide on)
-- App: System Events
-- Usage: osascript scripts/workflows/system-events/system-events-hide-dock.applescript
-- Generated by workflow-gen.py

do shell script "defaults write com.apple.Dock autohide -bool TRUE"
do shell script "killall Dock"
display notification "Dock hidden" with title "Dock"
