-- Create a new iMovie document
-- App: Imovie
-- Usage: osascript scripts/workflows/imovie/imovie-new-project.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "iMovie"
    activate
    make new document
end tell
