-- Toggle TV mute
-- App: Tv
-- Usage: osascript scripts/workflows/tv/tv-mute-toggle.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "TV"
    set mute to not mute
end tell
