-- Toggle play/pause
-- App: Tv
-- Triggers: playpause, toggle, play, pause
-- Category: Tv
-- Usage: osascript scripts/workflows/tv/tv-playpause.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "TV" to playpause
