-- Go to previous track
-- App: Tv
-- Usage: osascript scripts/workflows/tv/tv-previous-track.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "TV" to previous track
