-- Login to all accounts.
-- App: Messages
-- Usage: osascript scripts/auto-workflows/messages/messages-login.applescript
-- Auto-generated by auto-gen.py
-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Messages"
    login
end tell
display notification "Done" with title "Messages: login"
