-- Switch Calendar to today view
-- App: Calendar
-- Usage: osascript scripts/workflows/calendar/calendar-show-today.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).
-- Concept: current date
--   Returns the current date and time as an AppleScript date object.

tell application "Calendar"
    activate
    view calendar at current date
    switch view to day view
end tell
