-- Switch Calendar to week view
-- App: Calendar
-- Usage: osascript scripts/workflows/calendar/calendar-show-week.applescript
-- Generated by workflow-gen.py

tell application "Calendar"
    activate
    switch view to week view
end tell
