-- Switch Calendar to today view
-- App: Calendar
-- Usage: osascript scripts/workflows/calendar/calendar-show-today.applescript
-- Generated by workflow-gen.py

tell application "Calendar"
    activate
    view calendar at current date
    switch view to day view
end tell
