-- Switch Calendar to week view
-- App: Calendar
-- Usage: osascript scripts/workflows/calendar/calendar-show-week.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Calendar"
    activate
    switch view to week view
end tell
