-- Switch Calendar to month view
-- App: Calendar
-- Usage: osascript scripts/workflows/calendar/calendar-show-month.applescript
-- Generated by workflow-gen.py

tell application "Calendar"
    activate
    switch view to month view
end tell
