-- Reload all calendars
-- App: Calendar
-- Usage: osascript scripts/workflows/calendar/calendar-reload.applescript
-- Generated by workflow-gen.py

tell application "Calendar"
    reload calendars
    display notification "Calendars reloaded" with title "Calendar"
end tell
