-- Switch Calendar to month view
-- App: Calendar
-- Usage: osascript scripts/workflows/calendar/calendar-show-month.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Calendar"
    activate
    switch view to month view
end tell
