-- Pause the currently-playing slideshow.
-- App: Photos
-- Usage: osascript scripts/auto-workflows/photos/photos-pause-slideshow.applescript
-- Auto-generated by auto-gen.py
-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Photos"
    pause slideshow
end tell
display notification "Done" with title "Photos: pause slideshow"
