-- Start a new audio recording
-- App: Quicktime
-- Usage: osascript scripts/workflows/quicktime/quicktime-new-audio-recording.applescript
-- Generated by workflow-gen.py

tell application "QuickTime Player"
    activate
    new audio recording
end tell
