-- Start a new movie recording
-- App: Quicktime
-- Usage: osascript scripts/workflows/quicktime/quicktime-new-movie-recording.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "QuickTime Player"
    activate
    new movie recording
end tell
