-- Start a new audio recording
-- App: Quicktime
-- Usage: osascript scripts/workflows/quicktime/quicktime-new-audio-recording.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "QuickTime Player"
    activate
    new audio recording
end tell
