-- Start a new movie recording
-- App: Quicktime
-- Usage: osascript scripts/workflows/quicktime/quicktime-new-movie-recording.applescript
-- Generated by workflow-gen.py

tell application "QuickTime Player"
    activate
    new movie recording
end tell
