-- Start a new screen recording
-- App: Quicktime
-- Usage: osascript scripts/workflows/quicktime/quicktime-new-screen-recording.applescript
-- Generated by workflow-gen.py

tell application "QuickTime Player"
    activate
    new screen recording
end tell
