-- List all available Shortcuts
-- App: Shortcuts
-- Usage: osascript scripts/workflows/shortcuts/shortcuts-list-shortcuts.applescript
-- Generated by workflow-gen.py

set output to do shell script "shortcuts list"
set the clipboard to output
display notification "Copied shortcut list to clipboard" with title "Shortcuts"
