-- Run a Shortcut with text input
-- App: Shortcuts
-- Usage: osascript scripts/workflows/shortcuts/shortcuts-run-shortcut-with-input.applescript
-- Generated by workflow-gen.py

set sName to text returned of (display dialog "Shortcut name:" default answer "")
set input to text returned of (display dialog "Input:" default answer "")
do shell script "echo " & quoted form of input & " | shortcuts run " & quoted form of sName
display notification "Ran: " & sName with title "Shortcuts"
