-- Run a named Shortcut
-- App: Shortcuts
-- Usage: osascript scripts/workflows/shortcuts/shortcuts-run-shortcut.applescript
-- Generated by workflow-gen.py

set sName to text returned of (display dialog "Shortcut name:" default answer "")
do shell script "shortcuts run " & quoted form of sName
display notification "Ran: " & sName with title "Shortcuts"
