-- Create a new Automator workflow document
-- App: Automator
-- Usage: osascript scripts/workflows/automator/automator-new-workflow.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Automator"
    activate
    make new document
end tell
