-- Reposition to beginning of current track or go to previous track if already at start of current track
-- App: Music
-- Usage: osascript scripts/auto-workflows/music/music-back-track.applescript
-- Auto-generated by auto-gen.py
-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Music"
    back track
end tell
display notification "Done" with title "Music: back track"
