-- Disable fast forward/rewind and resume playback, if playing.
-- App: Music
-- Usage: osascript scripts/auto-workflows/music/music-resume.applescript
-- Auto-generated by auto-gen.py
-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Music"
    resume
end tell
display notification "Done" with title "Music: resume"
