-- Play the current track or the specified track or file.
-- App: Music
-- Usage: osascript scripts/auto-workflows/music/music-play.applescript
-- Auto-generated by auto-gen.py
-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Music"
    play
end tell
display notification "Done" with title "Music: play"
