-- Skip backwards in a playing track
-- App: Music
-- Usage: osascript scripts/auto-workflows/music/music-rewind.applescript
-- Auto-generated by auto-gen.py
-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Music"
    rewind
end tell
display notification "Done" with title "Music: rewind"
