-- Jump forward 30 seconds
-- App: Music
-- Usage: osascript scripts/workflows/music/music-seek-forward-30.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Music"
    set player position to (player position + 30)
end tell
