-- Toggle Music fullscreen mode
-- App: Music
-- Usage: osascript scripts/workflows/music/music-toggle-fullscreen.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set full screen to not full screen
end tell
