-- Jump forward 30 seconds
-- App: Music
-- Usage: osascript scripts/workflows/music/music-seek-forward-30.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set player position to (player position + 30)
end tell
