-- Rate the current track 2 stars
-- App: Music
-- Usage: osascript scripts/workflows/music/music-rating-2-stars.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set rating of current track to 40
    display notification "Rated 2 stars: " & name of current track with title "Music"
end tell
