-- Favorite the current track
-- App: Music
-- Usage: osascript scripts/workflows/music/music-love-current.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set favorited of current track to true
    display notification "Favorited: " & name of current track with title "Music"
end tell
