-- Clear rating of current track
-- App: Music
-- Usage: osascript scripts/workflows/music/music-rating-0-stars.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set rating of current track to 0
    display notification "Rating cleared: " & name of current track with title "Music"
end tell
