-- Rate the current track 3 stars
-- App: Music
-- Usage: osascript scripts/workflows/music/music-rating-3-stars.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set rating of current track to 60
    display notification "Rated 3 stars: " & name of current track with title "Music"
end tell
