-- Show how many times current track was played
-- App: Music
-- Usage: osascript scripts/workflows/music/music-played-count-current.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set t to current track
    display notification "Played " & (played count of t as text) & " times" with title (name of t)
end tell
