-- Rate the current track 5 stars
-- App: Music
-- Usage: osascript scripts/workflows/music/music-rating-5-stars.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set rating of current track to 100
    display notification "Rated 5 stars: " & name of current track with title "Music"
end tell
