-- Jump backward 30 seconds
-- App: Music
-- Usage: osascript scripts/workflows/music/music-seek-backward-30.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set p to player position
    if p > 30 then
        set player position to (p - 30)
    else
        set player position to 0
    end if
end tell
