-- Choose a playlist to play
-- App: Music
-- Usage: osascript scripts/workflows/music/music-play-playlist.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set pNames to name of every user playlist
    set chosen to choose from list pNames with title "Music" with prompt "Choose playlist:"
    if chosen is not false then
        play user playlist (item 1 of chosen)
        display notification "Playing: " & (item 1 of chosen) with title "Music"
    end if
end tell
