-- Reveal current track in Music library
-- App: Music
-- Usage: osascript scripts/workflows/music/music-reveal-current.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Music"
    reveal current track
    activate
end tell
