-- Toggle visual effects on/off
-- App: Music
-- Usage: osascript scripts/workflows/music/music-toggle-visuals.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set visuals enabled to not visuals enabled
end tell
