-- Dislike the current track and skip
-- App: Music
-- Usage: osascript scripts/workflows/music/music-dislike-current.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set disliked of current track to true
    display notification "Disliked: " & name of current track with title "Music"
    next track
end tell
