-- Show stream title and URL if streaming
-- App: Music
-- Usage: osascript scripts/workflows/music/music-current-stream-info.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set t to current stream title
    set u to current stream URL
    if t is "" and u is "" then
        display notification "Not streaming" with title "Music"
    else
        display notification u with title t
    end if
end tell
