-- Rate the current track 4 stars
-- App: Music
-- Usage: osascript scripts/workflows/music/music-rating-4-stars.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set rating of current track to 80
    display notification "Rated 4 stars: " & name of current track with title "Music"
end tell
