-- Toggle equalizer on/off
-- App: Music
-- Usage: osascript scripts/workflows/music/music-toggle-eq.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set EQ enabled to not EQ enabled
    if EQ enabled then
        display notification "EQ ON" with title "Music"
    else
        display notification "EQ OFF" with title "Music"
    end if
end tell
