-- Toggle Music mute
-- App: Music
-- Usage: osascript scripts/workflows/music/music-mute-toggle.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set mute to not mute
end tell
