-- Decrease Music volume by 10
-- App: Music
-- Usage: osascript scripts/workflows/music/music-volume-down.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set v to sound volume
    if v - 10 < 0 then
        set sound volume to 0
    else
        set sound volume to v - 10
    end if
end tell
