-- Toggle visual effects on/off
-- App: Music
-- Usage: osascript scripts/workflows/music/music-toggle-visuals.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Music"
    set visuals enabled to not visuals enabled
end tell
