-- Reveal current track in Music library
-- App: Music
-- Usage: osascript scripts/workflows/music/music-reveal-current.applescript
-- Generated by workflow-gen.py

tell application "Music"
    reveal current track
    activate
end tell
