-- Toggle Music fullscreen mode
-- App: Music
-- Usage: osascript scripts/workflows/music/music-toggle-fullscreen.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Music"
    set full screen to not full screen
end tell
