-- Rate the current track 1 star
-- App: Music
-- Usage: osascript scripts/workflows/music/music-rating-1-star.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set rating of current track to 20
    display notification "Rated 1 star: " & name of current track with title "Music"
end tell
