-- Skip to next track
-- App: Music
-- Usage: osascript scripts/workflows/music/music-next-track.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Music" to next track
