-- Create a new empty playlist
-- App: Music
-- Usage: osascript scripts/workflows/music/music-create-playlist.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set pName to text returned of (display dialog "New playlist name:" default answer "My Playlist")
    make new user playlist with properties {name:pName}
    display notification "Created: " & pName with title "Music"
end tell
