-- Show all user playlists as notification
-- App: Music
-- Usage: osascript scripts/workflows/music/music-list-playlists.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set pNames to name of every user playlist
    set output to ""
    repeat with p in pNames
        set output to output & p & ", "
    end repeat
    display dialog output with title "Your Playlists" buttons {"OK"} default button "OK"
end tell
