-- Show lyrics of current track
-- App: Music
-- Usage: osascript scripts/workflows/music/music-get-lyrics.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set t to current track
    set l to lyrics of t
    if l is "" then
        display dialog "No lyrics found for: " & name of t with title "Music" buttons {"OK"} default button "OK"
    else
        display dialog l with title (name of t & " — Lyrics") buttons {"OK"} default button "OK"
    end if
end tell
