-- Show total track count in library
-- App: Music
-- Usage: osascript scripts/workflows/music/music-count-library.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set c to count of tracks of library playlist 1
    display notification (c as text) & " tracks in library" with title "Music"
end tell
