-- Toggle shuffle mode
-- App: Music
-- Usage: osascript scripts/workflows/music/music-toggle-shuffle.applescript
-- Generated by workflow-gen.py

tell application "Music"
    set shuffle enabled to not shuffle enabled
    if shuffle enabled then
        display notification "Shuffle ON" with title "Music"
    else
        display notification "Shuffle OFF" with title "Music"
    end if
end tell
