-- Show current track as notification
-- App: Music
-- Usage: osascript scripts/workflows/music/music-now-playing.applescript
-- Generated by workflow-gen.py

tell application "Music"
    if player state is playing then
        set t to name of current track
        set a to artist of current track
        set al to album of current track
        display notification a & " — " & al with title t
    else
        display notification "Nothing playing" with title "Music"
    end if
end tell
