-- Create a new Keynote presentation
-- App: Keynote
-- Usage: osascript scripts/workflows/keynote/keynote-new-presentation.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Keynote"
    activate
    make new document
end tell
