-- Stop the currently playing slideshow
-- App: Photos
-- Usage: osascript scripts/workflows/photos/photos-stop-slideshow.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Photos"
    stop slideshow
end tell
