-- Count favorited photos
-- App: Photos
-- Usage: osascript scripts/workflows/photos/photos-favorites-count.applescript
-- Generated by workflow-gen.py

tell application "Photos"
    set favs to every media item whose favorite is true
    display notification (count of favs) & " favorites" with title "Photos"
end tell
