-- Search Photos library
-- App: Photos
-- Usage: osascript scripts/workflows/photos/photos-search.applescript
-- Generated by workflow-gen.py

tell application "Photos"
    activate
    set q to text returned of (display dialog "Search Photos:" default answer "")
    search for q
end tell
