-- Start a slideshow of selected photos
-- App: Photos
-- Usage: osascript scripts/workflows/photos/photos-start-slideshow.applescript
-- Generated by workflow-gen.py

tell application "Photos"
    activate
    set sel to selection
    if sel is not {} then
        start slideshow using sel
    else
        display notification "Select photos first" with title "Photos"
    end if
end tell
