-- Tell the application to reload all calendar files contents
-- App: Calendar
-- Usage: osascript scripts/auto-workflows/calendar/calendar-reload-calendars.applescript
-- Auto-generated by auto-gen.py
-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Calendar"
    reload calendars
end tell
display notification "Done" with title "Calendar: reload calendars"
