-- Create a new blank Numbers spreadsheet
-- App: Numbers
-- Usage: osascript scripts/workflows/numbers/numbers-new-spreadsheet.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Numbers"
    activate
    make new document
end tell
