-- Create a new blank Pages document
-- App: Pages
-- Usage: osascript scripts/workflows/pages/pages-new-document.applescript
-- Generated by workflow-gen.py

-- Concept: tell application ... end tell
--   Sends Apple Events to an app. The app must have a scripting dictionary (sdef).

tell application "Pages"
    activate
    make new document
end tell
